scheduler:
  max_lr: 1e-2

arch:
  f_e:
    dimension: 2
    nr_fno_layers: 4
    fno_modes: 12
    padding: 9
  f_p:
    dimension: 2
    nr_fno_layers: 4
    fno_modes: 12
    padding: 9
  f_E:
    dimension: 2
    nr_fno_layers: 4
    fno_modes: 12
    padding: 9
  f_B:
    dimension: 2
    nr_fno_layers: 4
    fno_modes: 12
    padding: 9

training:
  rec_validation_freq: 1000
  rec_inference_freq: 2000
  rec_monitor_freq: 1000
  rec_constraint_freq: 100
  max_steps: 10000
  resolution:
  weights:
    pde_weight: 0.1
    constraint_weight: 1.

batch_size:
  pde: 1000
  boundary: 1000
